apiVersion: v1
kind: Service
metadata:
  name: emitter-external
spec:
  type: NodePort
  selector:
    app: broker
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: 8080
      name: http
    - port: 8443
      nodePort: 30443
      targetPort: 8443
      name: https
