image: ghcr.io/openfaas/mqtt-connector:0.4.3
replicas: 1

topic: iot-uit/room-status

# For use with emitter.io
trimChannelKey: false

contentType: application/json

broker: tcp://broker.hivemq.com:1883
clientID: "openfaas-gateway"
authPassword: ""

upstream_timeout: 30s # Maximum duration for an invocation
rebuild_interval: 15s
asyncInvoke: false # Invoke via NATS using the function's asynchronous route
basic_auth: true
gateway_url: https://faas.thu4n.dev

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  # limits:
  #   memory: "256Mi"
  #   cpu: "100m"

nodeSelector: {}
tolerations: []
affinity: {}
